package com.jzr.bedside.db.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jzr.bedside.db.entity.BedInfoBeanDb;

import com.jzr.bedside.db.database.BedInfoBeanDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bedInfoBeanDbDaoConfig;

    private final BedInfoBeanDbDao bedInfoBeanDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bedInfoBeanDbDaoConfig = daoConfigMap.get(BedInfoBeanDbDao.class).clone();
        bedInfoBeanDbDaoConfig.initIdentityScope(type);

        bedInfoBeanDbDao = new BedInfoBeanDbDao(bedInfoBeanDbDaoConfig, this);

        registerDao(BedInfoBeanDb.class, bedInfoBeanDbDao);
    }
    
    public void clear() {
        bedInfoBeanDbDaoConfig.clearIdentityScope();
    }

    public BedInfoBeanDbDao getBedInfoBeanDbDao() {
        return bedInfoBeanDbDao;
    }

}
